name: Vite CI/CD

on:
  push:
    branches: ['gh-pages'] # 触发分支
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm' # 使用 pnpm 缓存

      # 依赖安装与构建
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build:docs

      # 部署到 GitHub Pages（示例）
      - name: Deploy to Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: demo # Vite 默认输出目录
          clean: true
